### ISSUE TITLE
directly pull data from WHO website. 

### ISSUE THREAD

**Issue by yy** [covid19-data/covid19-data#4]
(updated) We are currently pulling the data from Our World in Data: https://github.com/covid19-data/covid19-data/tree/master/data_sources/our_world_in_data which is a cleaned version of WHO's daily reports. Although it seems to be working now, it may fail in the future. I think it's good to have less dependency. 

Because WHO provides data in PDF 😱, one needs to parse PDFs. 
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports

**Comment by abenrob** [comment]
The issue here is that the format of the situation report has changed several times since the outbreak began...
I _did_ find this: https://ourworldindata.org/coronavirus-source-data, the csvs of which I am fetching directly i.e. [here](https://observablehq.com/@abenrob/comparing-covid-19-growth).
The WHO numbers are a bit behind the official country reports, most likely because these numbers need to be reported to the WHO in an official manner prior to incorporation into the WHO counts. I _do_ feel like the WHO (perhaps from the OurWorldInData sources should be the backbone of the dataset, and pipelines for individual countries will have to be developed to override the numbers for these countries.

**Comment by yy** [comment]
Thanks! Actually, right now we're pulling data from the Our World in Data. See: https://github.com/covid19-data/covid19-data/tree/master/data_sources/our_world_in_data

Yes, I agree that this can be the backbone, with some country- or state-level overrides to produce the most up-to-date dataset.

**Comment by yy** [comment]
Our World in Data switched to ECDC. WHO seems to be lagging a lot and provides only PDFs.
